# Лабораторная работа 1.4 
Трунов Антон М8О-304Б Вариант 16

# Задание
Реализовать метод вращений в виде программы, задавая в качестве входных данных матрицу и точность вычислений. Используя разработанное программное обеспечение, найти собственные значения и собственные векторы симметрических матриц. Проанализировать зависимость погрешности вычислений от числа итераций. 
\begin{pmatrix}
8 & -3 & 9 \\
-3 & 8 & -2 \\
9 & -2 & -8 \\
\end{pmatrix}

In [5]:
import numpy as np

def jacobi_eigen(A,eps=1e-3, maxiter = 1000):
    niter = 0
    N = A.shape[0]
    u = np.eye(N)
    t = [abs(A[i, j]) for i in range(N) for j in range(N) if i < j] #получение списка элементов стоящих выше диагонали
    Lam = np.copy(A)
    while np.linalg.norm(t) > eps and niter < maxiter:
        test = np.linalg.norm(t)
        a_ij = np.amax(t) #поиск максимального среди них
        ij = np.where(abs(Lam) == a_ij) #поиск индекса максимального элемента
        i,j = ij[0][0],ij[1][0]
        Phi = 0.5*np.arctan(2*A[i,j]/(A[i,i]-A[j,j])) if A[i,i] != A[j,j] else np.pi/4
        U = np.eye(N)
        U[i,j] = np.sin(Phi)
        U[j,i] = -np.sin(Phi)
        U[i,i]=U[j,j] = np.cos(Phi)
        A = np.copy(Lam)
        for m in range(i,j+1,j-i):
            for n in range(N):
                Lam[m,n] = np.inner(U[m, :], A[:, n])
        U[i,j],U[j,i]= U[j,i],U[i,j]
        A = np.copy(Lam)
        for m in range(i,j+1,j-i):
            for n in range(N):
                Lam[n,m] = np.inner(A[n,:],U[:,m])
        t = [abs(Lam[i, j]) for i in range(N) for j in range(N) if i < j]
        niter += 1
        u = u @ U
    return Lam,niter,u


In [6]:
A = np.array([[8,-3,9],[-3,8,-2],[9,-2,-8]],dtype=float)
Lam,niter,U = jacobi_eigen(np.copy(A))
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)
print("A:\n",A)
print("Eigenvalues:",[Lam[i,i] for i in range(len(Lam[0,:]))],"\nNumber of iterations:",niter)
print("Eigenvectors matrix:\n",U)


A:
 [[ 8. -3.  9.]
 [-3.  8. -2.]
 [ 9. -2. -8.]]
Eigenvalues: [14.11433981634089, 5.945408489747225, -12.059748306088107] 
Number of iterations: 7
Eigenvectors matrix:
 [[ 0.783  0.471 -0.405]
 [-0.504  0.863  0.03 ]
 [ 0.364  0.18   0.914]]
