# Лабораторная работа 1.2
Трунов Антон М8О-304Б Вариант 16

# Задание
Реализовать метод прогонки в виде программы, задавая в качестве входных данных ненулевые элементы матрицы системы и вектор правых частей. Используя разработанное программное обеспечение, решить СЛАУ с трехдиагональной матрицей.
\begin{cases}
18x_1 - 9x_2 = -81 \\
2x_1 - 9x_2 - 4x_3 = 71 \\
-9x_2 + 21x_3 - 8x_4 = -39 \\
-4x_3 - 10x_4 + 5x_5 = 64 \\
7x_4 + 12x_5 = 3 \\
\end{cases}

In [2]:
import numpy as np

def TDMA(A,d):
    N = len(d)
    x = np.zeros(N)
    P = np.zeros(N)
    Q = np.zeros(N)
    P[0] = -A[0,1]/A[0,0]
    Q[0] = d[0]/A[0,0]
    for i in range(1,N-1):
        P[i]=-A[i,i+1]/(A[i,i]+A[i,i-1]*P[i-1])
        Q[i]=(d[i]-A[i,i-1]*Q[i-1])/(A[i,i]+A[i,i-1]*P[i-1])
    x[N-1] = (d[N-1]-A[N-1,N-2]*Q[N-2])/(A[N-1,N-1]+A[N-1,N-2]*P[N-2])
    for i in range(N-2,-1,-1):
        x[i] = P[i]*x[i+1]+Q[i]
    return x

In [3]:
d=np.array([-81,71,-39,64,3],dtype=float)
A = np.array([[18,-9,0,0,0],[2,-9,-4,0,0],[0,-9,21,-8,0],[0,0,-4,-10,5],[0,0,0,7,12]],dtype=float)
x= TDMA(A,d)
print("A:\n",A,"\n","d:",d,"\n","Solution:",x)
print("Solution using linalg.solve:",np.linalg.solve(A,d))

A:
 [[ 18.  -9.   0.   0.   0.]
 [  2.  -9.  -4.   0.   0.]
 [  0.  -9.  21.  -8.   0.]
 [  0.   0.  -4. -10.   5.]
 [  0.   0.   0.   7.  12.]] 
 d: [-81.  71. -39.  64.   3.] 
 Solution: [-8. -7. -6. -3.  2.]
Solution using linalg.solve: [-8. -7. -6. -3.  2.]
