# Лабораторная работа 1.3
Трунов Антон М8О-304Б Вариант 16

# Задание
Реализовать метод простых итераций и метод Зейделя в виде программ, задавая в качестве входных данных матрицу системы, вектор правых частей и точность вычислений. Используя разработанное программное обеспечение, решить СЛАУ. Проанализировать количество итераций, необходимое для достижения заданной точности.
\begin{cases}
21x_1 - 6x_2 - 9x_3 - 4x_4 = 127 \\
-6x_1 + 20x_2 - 4x_3 + 2x_4 = -144 \\
-2x_1 - 7x_2 - 20x_3 + 3x_4 = 236 \\
4x_1 + 9x_2 + 6x_3 + 24x_4 = -5 \\
\end{cases}

In [5]:
import numpy as np

In [6]:
def norm(B,d):
    maxsum = 0
    for i in range(len(b)):
        sum =np.sum(np.abs(B[i,:]*d[i]))
        if sum >= maxsum:
            maxsum = sum
    return maxsum

# I.  Jacobi iteration

Given

$$
A x = b
$$

separate the diagonal part $D$,

$$ A = D + (A - D) $$

and write

$$
x = D^{-1} (D - A) x + D^{-1} b\;.
$$

Then iterate

$$
x_{n + 1} = B x_{n} + c\;,
$$

where 

$$
B = D^{-1} (A - D) \qquad \text{and} \qquad c = D^{-1} b
$$


In [7]:
def jacobi(A,b,eps=1e-5,maxiter=1000):
    d = 1./np.diag(A)
    np.fill_diagonal(A,0)
    x0 = b * d
    x = np.copy(x0)
    normB = norm(A,d) #B=D_-1(D-A)
    for i in range(maxiter):#x1 = Bx0+c, c=D_-1*b
        for j in range(len(b)):
            x[j]=(-np.inner(A[j,:],x0)+b[j])*d[j]
        if np.linalg.norm(x-x0)*normB/(1-normB) < eps:
            return x,i
        x0 = np.copy(x)
    return x,i

# Il.  Seidel iteration

Given

$$
A x = b
$$

$$ A = L + D + U $$

Where $L$ - lower triangular matrix, $U$ - upper triangular and $D$ - diagonal of $A$ 

$$
Lx_{n+1} + Dx_{n+1} + Ux_n = b\;.
$$

Then iterate

$$
x_{n + 1} = B x_{n} + c\;,
$$

where 

$$
B = -(L+D)^{-1} U \qquad \text{and} \qquad c = (L+D)^{-1} b
$$


In [8]:
def seidel(A,b,eps=1e-5,maxiter=1000):#(L+D+U)x=b, Lx1+Dx1+Ux0=b,x1=-(L+D)_-1*Ux0+(L+D)_-1*b
    d = 1. / np.diag(A)
    np.fill_diagonal(A, 0)
    x0 = b * d
    x = np.copy(x0)
    normB = norm(A,d)
    normC= norm(np.copy(np.triu(A,-1)),np.ones(len(b)))#C = U
    for i in range(maxiter):
        for j in range(len(b)):
            x[j]=(-np.inner(A[j,:j+1],x[:j+1])-np.inner(A[j,j+1:],x0[j+1:])+b[j])*d[j]
        if np.linalg.norm(x - x0)*normC/(1-normB) < eps:
            return x, i
        x0 = np.copy(x)
    return x, i

In [9]:
A = np.array([[21,-6,-9,-4],[-6,20,-4,2],[-2,-7,-20,3],[4,9,6,24]],dtype=float)
b = np.array([127,-144,236,-5],dtype=float)
print("Input:\n",A,"\n",b)
x , niter = jacobi(np.copy(A),np.copy(b))
np.set_printoptions(precision=3)
print("Jacobi:",x,"\n","Number of iterations:",niter)
x , niter = seidel(np.copy(A),np.copy(b))
print("Seidel:",x,"\n","Number of iterations:",niter)
print("linalg:",np.linalg.solve(A,b))


Input:
 [[ 21.  -6.  -9.  -4.]
 [ -6.  20.  -4.   2.]
 [ -2.  -7. -20.   3.]
 [  4.   9.   6.  24.]] 
 [ 127. -144.  236.   -5.]
Jacobi: [ 1. -9. -8.  5.] 
 Number of iterations: 22
Seidel: [ 1. -9. -8.  5.] 
 Number of iterations: 11
linalg: [ 1. -9. -8.  5.]
